USE [master]
GO
/****** Object:  Database [Gestao]    Script Date: 08/02/2023 21:57:19 ******/
CREATE DATABASE [Gestao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gestao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\Gestao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gestao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\Gestao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Gestao] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gestao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Gestao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Gestao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Gestao] SET ARITHABORT OFF 
GO
ALTER DATABASE [Gestao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Gestao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Gestao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Gestao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Gestao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Gestao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Gestao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Gestao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Gestao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Gestao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Gestao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Gestao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Gestao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Gestao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Gestao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Gestao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Gestao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Gestao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Gestao] SET  MULTI_USER 
GO
ALTER DATABASE [Gestao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Gestao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Gestao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Gestao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Gestao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Gestao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Gestao] SET QUERY_STORE = OFF
GO
USE [Gestao]
GO
/****** Object:  Table [dbo].[GrupoUsuario]    Script Date: 08/02/2023 21:57:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrupoUsuario](
	[id_grupoUsuario] [int] IDENTITY(1,1) NOT NULL,
	[NomeGrupo] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_grupoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 08/02/2023 21:57:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[id_descricao] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_descricao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PermissaogrupoUsuario]    Script Date: 08/02/2023 21:57:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PermissaogrupoUsuario](
	[cod_GrupoUsuario] [int] NOT NULL,
	[cod_Permissao] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cod_GrupoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 08/02/2023 21:57:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Passoword] [varchar](20) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[CPF] [varchar](15) NOT NULL,
	[Ativo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsuarioGrupoUsuario]    Script Date: 08/02/2023 21:57:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioGrupoUsuario](
	[cod_usuario] [int] NULL,
	[cod_GrupoUsuario] [int] NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Gestao] SET  READ_WRITE 
GO
